version: '3.9'
services:
  rtmp:
    build: ./rtmp
    ports:
      - "1935:1935"
    container_name: rtmp_server
    volumes:
      - ./data:/tmp/hls
  auth:
    build: ./auth
    container_name: auth_server
  client:
    build: ./client
    ports:
      - "3006:3006"
    container_name: client